name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"   # se actualiza cada día
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }}
          user: SilvityCode

          # --- ESTADÍSTICAS GENERALES ---
          base: header, activity, repositories

          # --- LENGUAJES MÁS USADOS ---
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_colors: github
