name: GitHub Metrics
on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.36
        with:
          # Usa un token con permisos suficientes; crea un PAT si es privado
          token: ${{ secrets.PAT_TOKEN }}
          user: SilvityCode

          # Lista de bloques base sin espacios despu√©s de la coma
          base: header,activity,repositories

          # Plugins opcionales
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_colors: github

